unit testing for US005
Chottek/team404-api pull request #14
Opened 2021-09-06 09:56 UTC by Jackrwal

Additional unit testing for User stories up to US005

2021-09-06 12:39 UTC, SamuelChorvat requested changes
The new tests are not run when you type 'mvn test' or 'mvn -B test --file pom.xml'. Therefore they are not run by the Github Action, only the dummy test is being run.

2021-09-06 14:48 UTC, SamuelChorvat approved these changes

2021-09-09 10:48 UTC, Chottek commented on src/test/java/com/team404/kainosproject/unittests/service/BandServiceTest.java
> +                        {'name' : 'test sub competency', 'description' : "test indicator one"}, {'name' : 'test sub competency', 'description' : "test indicator two"},
Getting rid of this comment would be a good practice here, as this is a JSON result from api endpoint, easy to check

2021-09-09 10:48 UTC, Chottek approved these changes

2021-09-09 10:52 UTC, merged