Releasing US002 viewjobspecification
Chottek/team404-api pull request #6
Opened 2021-08-31 14:28 UTC by Jackrwal

US002 Released to mater after sign off form technical lead.

This allows the user to view specific Jobs's specifications with links to the Kainos Sharepoint

2021-08-31 16:01 UTC, SamuelChorvat requested changes
Compilation error in JobRole.java because the merge conflict was not resolved correctly, it still contains both versions including the '<<<<<<< HEAD', '=======' and '>>>>>>> master' tags. Same for JobRoleService and JobRoleRepository

2021-08-31 17:47 UTC, SamuelChorvat commented
Redone the merge conflicts but it needs to be checked/tested. US003 and US004 should be reverted to their original state before the merge attempt and once we know that US002 is still working we can merge US002 into them.

2021-09-02 13:06 UTC, SamuelChorvat approved these changes

2021-09-02 13:15 UTC, Chottek approved these changes

2021-09-02 13:17 UTC, merged