Releasing US003 viewjobcapability after sign off
Chottek/team404-api pull request #7
Opened 2021-08-31 14:31 UTC by Jackrwal

Releasing US003 onto master after sign off from technical lead.

This allows a user to view what capability a job belongs too

2021-08-31 17:49 UTC, SamuelChorvat requested changes
Can't be compiled after the merges.

2021-09-02 13:07 UTC, SamuelChorvat approved these changes

2021-09-02 13:16 UTC, Chottek commented on src/test/java/com/team404/kainosproject/integrationtests/JobRoleControllerTest.java
> +
Empty test here?

2021-09-02 13:17 UTC, Chottek approved these changes

2021-09-02 13:31 UTC, merged